title: No Fake Science
description: Site du collectif NoFakeScience.
author: NoFakeScience
email: nofakescience@gmail.com
url: "http://localhost:4000"
baseurl: ""

social_links:
  twitter: nofake_science
  facebook: nofakescience
  github: nofakescience/nofakescience.github.io

plugins: []
